const baseUrls = [
    
    // 'https://metro-kicks.cartpe.in/',
    // 'https://styleloop11.cartpe.in/',
    // 'https://spshoes.cartpe.in/',
    // 'https://trademarkstore.cartpe.in/',
    // 'https://reseller-orders.cartpe.in/',
    // 'https://greenenterprise.cartpe.in/',
    // 'https://4foxindia.cartpe.in/',
    // 'https://hmsales.cartpe.in/',
    // 'https://shoegallery66.cartpe.in/',
    'https://thecomfortzone.cartpe.in/',
    'https://hotkickss.cartpe.in/',
    'https://laceupshoe.cartpe.in/',
    'https://shoezerry1.cartpe.in/',
    'https://foot-shoppers.cartpe.in/',
    'https://sneaker-zone.cartpe.in/',
    'https://kamalenterprise.cartpe.in/',
    'https://bootsstudio.cartpe.in/',
    'https://opalitess.cartpe.in/',
    'https://le-brouges-resell.cartpe.in/',
    'https://myorders.cartpe.in/',
    'https://bismi-shoes.cartpe.in/',
    'https://hubsneaker.cartpe.in/',
    'https://oneshoess.cartpe.in/',
    'https://skicks2023.cartpe.in/',
    'https://thefashiontrendzmarketing.cartpe.in/',
    'https://mh-sneaker.cartpe.in/',
    'https://arsneakers.cartpe.in/',
    'https://utstore.cartpe.in/', //The website is blocked by admin.
    'https://supreme.cartpe.in/',
    'https://dmienterprisee.cartpe.in/',
    'https://mangoenterprise11.cartpe.in/',
    'https://classyslide.cartpe.in/',
    'https://benzershoes.in/',
    'https://ffhouse.cartpe.in/',
    'https://shoezone17.cartpe.in/',
    'https://reseller-store.cartpe.in/',
    'https://boot-gallery.cartpe.in/',
    'https://dropshipresellers.cartpe.in/',
    'https://ultimate-kicks.cartpe.in/',
    'https://firekicks.cartpe.in/',
    'https://signature-loafers-1.cartpe.in/',
    'https://shoefly1.cartpe.in/',
    'https://hypeshoe.cartpe.in/',
    'https://kicksmania777.cartpe.in/',
    'https://shoe-house-1.cartpe.in/',
    'https://shoebox-1.cartpe.in/',
    'https://luxurystoreresell.cartpe.in/',
    'https://shoetrendzreseller.cartpe.in/',
    'https://foot77loocker12.cartpe.in/',
    'https://shoeplanetin.cartpe.in/',
    'https://classyshoesreseller.cartpe.in/',
    'https://shoemartt.cartpe.in/',
];


export { baseUrls }