FROM ghcr.io/puppeteer/puppeteer:24.1.1

ENV PUPPETEER_SKIP_DOWNLOAD TRUE \

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /user/src/app

COPY package*.json ./
RUN npm ci
COPY ..
CMD ["node", "index.js"]